//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPKHO_CT
    {
        public string SoPhieuN { get; set; }
        public int STT { get; set; }
        public string MaHang { get; set; }
        public Nullable<double> SLNhap { get; set; }
        public Nullable<decimal> DGNhap { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual NHAPKHO NHAPKHO { get; set; }
    }
}
